### ISSUE TITLE
debug_vocab

### ISSUE THREAD

**Issue by nnn1988** [DeNeutoy/Decomposable_Attn#1]
Hi
thank you for sharing the code
I do not know what this file is in : 
  vocab = Vocab("/Users/markneumann/Documents/Machine_Learning/act-rte-inference/snli_1.0/debug_vocab.txt", dataset_path, 30000)

can you please help
Thank you in advance
Regards
Nujud

**Comment by DeNeutoy** [comment]
Hi,

You need to write a script which calls this function:

https://github.com/DeNeutoy/Decomposable_Attn/blob/master/Vocab.py#L38

This will write it out to a file which you can read in.
